spring.application.name=quiz

# CONFIGURAÇÃO H2 (em memoria)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONSOLE WEB DO H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Garante que os scripts SQL (como data.sql) sejam sempre executados
spring.sql.init.mode=always

# link para o banco de dados H2 :http://localhost:8080/h2-console